import {
  LANDINGPAGE_ROUTES,
  AUTH_ROUTES,
  BOOKING_ROUTES,
  PAYMENT_ROUTES,
  PROFILE_ROUTES,
  PARTNER_ROUTES,
  SUPERADMIN_ROUTES,
  UNAUTHORIZED_ROUTES
} from "./routes";

export const appRoutes = [
  ...LANDINGPAGE_ROUTES,
  ...AUTH_ROUTES,
  ...LANDINGPAGE_ROUTES,
  ...BOOKING_ROUTES,
  ...PROFILE_ROUTES,
  ...PAYMENT_ROUTES,
  ...PARTNER_ROUTES,
  ...SUPERADMIN_ROUTES,
  ...UNAUTHORIZED_ROUTES
];
